### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by Frigerius** [xhsun/gw2wrapper#24]
Hey, since PoF I'm getting this Exception, when requesting the AccountInformation

`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 16 column 14 path $.access
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at me.xhsun.guildwars2wrapper.SynchronousRequest.getAccountInfo(SynchronousRequest.java:201)`

Think you just have to Change the Access property from Access to List<Access> at Account.java, testing it and will update if it works this way.

Jep, just change Line 27 to List<Access> and line 61 List<Access> and it will work

**Comment by xhsun** [comment]
Thanks for letting me know!

**Comment by Frigerius** [comment]
Ah and u have to add PathOfFire to ur enums ;)
